#include "RTIMULib.h"

int main() {
    //  using RTIMULib here allows it to use the .ini file generated by
    //  RTIMULibDemo.
    RTIMUSettings *settings = new RTIMUSettings("RTIMULib");

    RTIMU *imu = RTIMU::createIMU(settings);

    if ((imu == NULL) || (imu->IMUType() == RTIMU_TYPE_NULL)) {
        printf("No IMU found\n");
        exit(1);
    }

    //  This is an opportunity to manually override any settings before the
    //  call IMUInit

    //  set up IMU
    imu->IMUInit();

    //  this is a convenient place to change fusion parameters
    imu->setSlerpPower(0.02);
    imu->setGyroEnable(true);
    imu->setAccelEnable(true);
    imu->setCompassEnable(true);

    while (imu->IMURead()) {
        RTIMU_DATA imuData = imu->getIMUData();

        printf("%s\n", RTMath::displayDegrees("", imuData.fusionPose));
    }
}
